stages:
  - main-build

variables:
  CONTAINER_REGISTRIES: |
    voxsoft/kube-synchro-scale
    voxmaster/kube-synchro-scale
    $CI_REGISTRY_IMAGE

Build:
  stage: main-build
  image: ezkrg/buildx:latest
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
    ## Create a set of tags for the image with multiple registries
    - for REGISTRY in $CONTAINER_REGISTRIES; do
        TAGS="$TAGS -t ${REGISTRY}:${CI_COMMIT_BRANCH}";
      done
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push $TAGS .
  except:
    - tags

Release:
  stage: main-build
  image: ezkrg/buildx:latest
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
    ## Create a set of tags for the image with multiple registries
    - for REGISTRY in $CONTAINER_REGISTRIES; do
        TAGS="$TAGS -t ${REGISTRY}:${CI_COMMIT_TAG} -t ${REGISTRY}:latest";
      done
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm64/v8,linux/amd64 --push $TAGS .
  only:
    - tags
