stages:
  - main-build

variables:
  GIT_DEPTH: "1"
  CONTAINER_REGISTRY: voxsoft/kube-synchro-scale

Build:
  stage: main-build
  image: ezkrg/buildx:latest
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push
        -t ${CONTAINER_REGISTRY}:${CI_COMMIT_BRANCH} .
  except:
    - tags

Release:
  stage: main-build
  image: ezkrg/buildx:latest
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD
    - docker buildx create --name mybuilder --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push
        -t ${CONTAINER_REGISTRY}:${CI_COMMIT_TAG} 
        -t ${CONTAINER_REGISTRY}:latest .
  only:
    - tags
